### PR TITLE
fix: support for any email domains

### LINKED ISSUE #12: Your homepage waitlist doesn't accept '.design' email domains
I tried joining the waitlist with a `*@*.design` email address, but it didn't like it much 😅

### PR DESCRIPTION
**Pull request by thara003**
## What kind of change does this PR introduce?

Support for any email domains

This PR fixes #12

### CODE REVIEW

File: apps/www/components/early-input.tsx [hunk 1]
```diff
@@ -12,7 +12,7 @@ const EarlyInput = () => {
   };
   const handleSubmit = async (e) => {
     e.preventDefault();
-    const regex = new RegExp(/^[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,4}$/i);
+    const regex = new RegExp(/^[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}$/i);
     if (!regex.test(email)) {
       toast.error("Please enter a valid email");
```
Comment (North8side2510) [inline apps/www/components/early-input.tsx:17]: Utc-09
